package de.mxscha.gemstones.datagen;

import de.mxscha.gemstones.block.ModBlocks;
import de.mxscha.gemstones.item.ModItems;
import net.minecraft.advancements.critereon.ItemPredicate;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.*;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.SmeltingRecipe;
import net.minecraftforge.common.crafting.conditions.IConditionBuilder;

import java.util.function.Consumer;

public class ModRecipeProvider extends RecipeProvider implements IConditionBuilder {

    public ModRecipeProvider(DataGenerator dataGenerator) {
        super(dataGenerator);
    }

    /**
     * TODO: furnace recipes (raw materials -> Ingots)
     * TODO: Armor Recipes TIN - FUSION_NETHERITE
     */

    @Override
    protected void buildCraftingRecipes(Consumer<FinishedRecipe> finishedRecipeConsumer) {
        ShapedRecipeBuilder.shaped(ModBlocks.SAPPHIRE_BLOCK.get()).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.RUBY_BLOCK.get()).define('E', ModItems.RUBY_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.CITRINE_BLOCK.get()).define('E', ModItems.CITRINE_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.AMETHYST_BLOCK.get()).define('E', ModItems.AMETHYST_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.DIOPSIDE_BLOCK.get()).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.JADE_BLOCK.get()).define('E', ModItems.JADE_GEM.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.CAERULA_BLOCK.get()).define('E', ModItems.CAERULA_INGOT.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.ENERGETIC_BLOCK.get()).define('E', ModItems.ENERGETIC_INGOT.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_energetic_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENERGETIC_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.TIN_BLOCK.get()).define('E', ModItems.TIN_INGOT.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.ENDER_BLOCK.get()).define('E', ModItems.ENDER_INGOT.get()).pattern("EEE").pattern("EEE").pattern("EEE").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.SAPPHIRE_GEM.get(), 9).requires(ModBlocks.SAPPHIRE_BLOCK.get(), 1).unlockedBy("has_another_sapphire_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.SAPPHIRE_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.RUBY_GEM.get(), 9).requires(ModBlocks.RUBY_BLOCK.get(), 1).unlockedBy("has_another_ruby_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.RUBY_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.CITRINE_GEM.get(), 9).requires(ModBlocks.CITRINE_BLOCK.get(), 1).unlockedBy("has_another_citrine_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.CITRINE_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.AMETHYST_GEM.get(), 9).requires(ModBlocks.AMETHYST_BLOCK.get(), 1).unlockedBy("has_another_amethyst_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.AMETHYST_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.DIOPSIDE_GEM.get(), 9).requires(ModBlocks.DIOPSIDE_BLOCK.get(), 1).unlockedBy("has_another_diopside_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.DIOPSIDE_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.JADE_GEM.get(), 9).requires(ModBlocks.JADE_BLOCK.get(), 1).unlockedBy("has_another_jade_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.JADE_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.CAERULA_INGOT.get(), 9).requires(ModBlocks.CAERULA_BLOCK.get(), 1).unlockedBy("has_another_caerula_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.CAERULA_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.ENERGETIC_INGOT.get(), 9).requires(ModBlocks.ENERGETIC_BLOCK.get(), 1).unlockedBy("has_another_energetic_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.ENERGETIC_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.TIN_INGOT.get(), 9).requires(ModBlocks.TIN_BLOCK.get(), 1).unlockedBy("has_another_tin_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.TIN_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.ENDER_INGOT.get(), 9).requires(ModBlocks.ENDER_BLOCK.get(), 1).unlockedBy("has_another_ender_block", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.ENDER_BLOCK.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_PLATE.get()).define('Q', ModItems.CAERULA_SHARD.get()).define('W', ModItems.JADE_GEM.get()).define('E', ModItems.ENDER_INGOT.get()).pattern("EQE").pattern("QWQ").pattern("EQE").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_INGOT.get()).define('Q', ModItems.CAERULA_SHARD.get()).define('W', ModItems.SAPPHIRE_GEM.get()).define('E', ModItems.RUBY_GEM.get()).define('R', ModItems.CITRINE_GEM.get()).define('T', ModItems.DIOPSIDE_GEM.get()).define('Z', ModItems.ENDER_PLATE.get()).pattern("QRQ").pattern("WZE").pattern("QTQ").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.INFUSED_ALLOY.get()).define('Q', ModItems.TIN_INGOT.get()).define('W', Items.IRON_INGOT).define('E', ModItems.OIL_ESSENCE.get()).pattern("QWQ").pattern("WEW").pattern("QWQ").unlockedBy("has_another_iron_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(Items.IRON_INGOT).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_SWORD.get()).define('/', Items.STICK).define('E', ModItems.TIN_INGOT.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.TIN_INGOT.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_AXE.get()).define('/', Items.STICK).define('E', ModItems.TIN_INGOT.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.TIN_INGOT.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_HOE.get()).define('/', Items.STICK).define('E', ModItems.TIN_INGOT.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_SWORD.get()).define('/', Items.STICK).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_AXE.get()).define('/', Items.STICK).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_HOE.get()).define('/', Items.STICK).define('E', ModItems.SAPPHIRE_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_SWORD.get()).define('/', Items.STICK).define('E', ModItems.RUBY_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.RUBY_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_AXE.get()).define('/', Items.STICK).define('E', ModItems.RUBY_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.RUBY_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_HOE.get()).define('/', Items.STICK).define('E', ModItems.RUBY_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_SWORD.get()).define('/', Items.STICK).define('E', ModItems.CITRINE_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.CITRINE_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_AXE.get()).define('/', Items.STICK).define('E', ModItems.CITRINE_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.CITRINE_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_HOE.get()).define('/', Items.STICK).define('E', ModItems.CITRINE_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_SWORD.get()).define('/', Items.STICK).define('E', ModItems.AMETHYST_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.AMETHYST_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_AXE.get()).define('/', Items.STICK).define('E', ModItems.AMETHYST_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.AMETHYST_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_HOE.get()).define('/', Items.STICK).define('E', ModItems.AMETHYST_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_SWORD.get()).define('/', Items.STICK).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_AXE.get()).define('/', Items.STICK).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_HOE.get()).define('/', Items.STICK).define('E', ModItems.DIOPSIDE_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_SWORD.get()).define('/', Items.STICK).define('E', ModItems.JADE_GEM.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.JADE_GEM.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_AXE.get()).define('/', Items.STICK).define('E', ModItems.JADE_GEM.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.JADE_GEM.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_HOE.get()).define('/', Items.STICK).define('E', ModItems.JADE_GEM.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_SWORD.get()).define('/', Items.STICK).define('E', ModItems.CAERULA_INGOT.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.CAERULA_INGOT.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_AXE.get()).define('/', Items.STICK).define('E', ModItems.CAERULA_INGOT.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.CAERULA_INGOT.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_HOE.get()).define('/', Items.STICK).define('E', ModItems.CAERULA_INGOT.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_SWORD.get()).define('/', Items.STICK).define('E', ModItems.ENDER_INGOT.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.ENDER_INGOT.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_AXE.get()).define('/', Items.STICK).define('E', ModItems.ENDER_INGOT.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.ENDER_INGOT.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_HOE.get()).define('/', Items.STICK).define('E', ModItems.ENDER_INGOT.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_SWORD.get()).define('/', Items.STICK).define('E', ModItems.FUSION_INGOT.get()).pattern("E").pattern("E").pattern("/").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_PICKAXE.get()).define('/', Items.STICK).define('E', ModItems.FUSION_INGOT.get()).pattern("EEE").pattern(" / ").pattern(" / ").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_AXE.get()).define('/', Items.STICK).define('E', ModItems.FUSION_INGOT.get()).pattern("EE ").pattern("E/ ").pattern(" / ").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_SHOVEL.get()).define('/', Items.STICK).define('E', ModItems.FUSION_INGOT.get()).pattern("E").pattern("/").pattern("/").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_HOE.get()).define('/', Items.STICK).define('E', ModItems.FUSION_INGOT.get()).pattern("EE ").pattern(" / ").pattern(" / ").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_HELMET.get()).define('T', ModItems.TIN_INGOT.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_CHESTPLATE.get()).define('T', ModItems.TIN_INGOT.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_LEGGINGS.get()).define('T', ModItems.TIN_INGOT.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.TIN_BOOTS.get()).define('T', ModItems.TIN_INGOT.get()).pattern("T T").pattern("T T").unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_HELMET.get()).define('T', ModItems.SAPPHIRE_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_CHESTPLATE.get()).define('T', ModItems.SAPPHIRE_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_LEGGINGS.get()).define('T', ModItems.SAPPHIRE_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.SAPPHIRE_BOOTS.get()).define('T', ModItems.SAPPHIRE_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_HELMET.get()).define('T', ModItems.RUBY_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_CHESTPLATE.get()).define('T', ModItems.RUBY_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_LEGGINGS.get()).define('T', ModItems.RUBY_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.RUBY_BOOTS.get()).define('T', ModItems.RUBY_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_HELMET.get()).define('T', ModItems.CITRINE_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_CHESTPLATE.get()).define('T', ModItems.CITRINE_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_LEGGINGS.get()).define('T', ModItems.CITRINE_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CITRINE_BOOTS.get()).define('T', ModItems.CITRINE_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_HELMET.get()).define('T', ModItems.AMETHYST_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_CHESTPLATE.get()).define('T', ModItems.AMETHYST_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_LEGGINGS.get()).define('T', ModItems.AMETHYST_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.AMETHYST_BOOTS.get()).define('T', ModItems.AMETHYST_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_HELMET.get()).define('T', ModItems.DIOPSIDE_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_CHESTPLATE.get()).define('T', ModItems.DIOPSIDE_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_LEGGINGS.get()).define('T', ModItems.DIOPSIDE_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.DIOPSIDE_BOOTS.get()).define('T', ModItems.DIOPSIDE_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_HELMET.get()).define('T', ModItems.JADE_GEM.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_CHESTPLATE.get()).define('T', ModItems.JADE_GEM.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_LEGGINGS.get()).define('T', ModItems.JADE_GEM.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.JADE_BOOTS.get()).define('T', ModItems.JADE_GEM.get()).pattern("T T").pattern("T T").unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_HELMET.get()).define('T', ModItems.CAERULA_INGOT.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_CHESTPLATE.get()).define('T', ModItems.CAERULA_INGOT.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_LEGGINGS.get()).define('T', ModItems.CAERULA_INGOT.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.CAERULA_BOOTS.get()).define('T', ModItems.CAERULA_INGOT.get()).pattern("T T").pattern("T T").unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_HELMET.get()).define('T', ModItems.ENDER_INGOT.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_CHESTPLATE.get()).define('T', ModItems.ENDER_INGOT.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_LEGGINGS.get()).define('T', ModItems.ENDER_INGOT.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.ENDER_BOOTS.get()).define('T', ModItems.ENDER_INGOT.get()).pattern("T T").pattern("T T").unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_HELMET.get()).define('T', ModItems.FUSION_INGOT.get()).pattern("TTT").pattern("T T").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_CHESTPLATE.get()).define('T', ModItems.FUSION_INGOT.get()).pattern("T T").pattern("TTT").pattern("TTT").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_LEGGINGS.get()).define('T', ModItems.FUSION_INGOT.get()).pattern("TTT").pattern("T T").pattern("T T").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModItems.FUSION_BOOTS.get()).define('T', ModItems.FUSION_INGOT.get()).pattern("T T").pattern("T T").unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.BASIC_MACHINE_FRAME.get()).define('E', ModItems.ENERGETIC_INGOT.get()).define('I', Items.IRON_BLOCK).define('C', Items.COPPER_INGOT).define('T', ModItems.TIN_INGOT.get()).pattern("ETE").pattern("CIC").pattern("ETE").unlockedBy("has_another_iron_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(Items.IRON_INGOT).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.DIAMOND_MACHINE_FRAME.get()).define('E', ModItems.ENERGETIC_INGOT.get()).define('B', ModBlocks.BASIC_MACHINE_FRAME.get()).define('R', Items.REDSTONE).define('D', Items.DIAMOND).pattern("EDE").pattern("RBR").pattern("EDE").unlockedBy("has_another_basic_machine_frame", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.BASIC_MACHINE_FRAME.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.OIL_GENERATOR.get()).define('E', ModItems.ENERGETIC_INGOT.get()).define('B', ModBlocks.BASIC_MACHINE_FRAME.get()).define('R', Items.REDSTONE_BLOCK).define('T', ModItems.TIN_INGOT.get()).pattern("TRT").pattern("EBE").pattern("TRT").unlockedBy("has_another_basic_machine_frame", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.BASIC_MACHINE_FRAME.get()).build())).save(finishedRecipeConsumer);
        ShapedRecipeBuilder.shaped(ModBlocks.GEM_BURNER.get()).define('E', ModItems.ENERGETIC_INGOT.get()).define('B', ModBlocks.DIAMOND_MACHINE_FRAME.get()).define('R', Items.REDSTONE_BLOCK).define('D', Items.DIAMOND).pattern("ERE").pattern("DBD").pattern("ERE").unlockedBy("has_another_diamond_machine_frame", inventoryTrigger(ItemPredicate.Builder.item().of(ModBlocks.DIAMOND_MACHINE_FRAME.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.TIN_PAXEL.get()).requires(ModItems.TIN_SWORD.get()).requires(ModItems.TIN_PICKAXE.get()).requires(ModItems.TIN_AXE.get()).requires(ModItems.TIN_SHOVEL.get()).requires(ModItems.TIN_HOE.get()).unlockedBy("has_another_tin_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.TIN_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.SAPPHIRE_PAXEL.get()).requires(ModItems.SAPPHIRE_SWORD.get()).requires(ModItems.SAPPHIRE_PICKAXE.get()).requires(ModItems.SAPPHIRE_AXE.get()).requires(ModItems.SAPPHIRE_SHOVEL.get()).requires(ModItems.SAPPHIRE_HOE.get()).unlockedBy("has_another_sapphire_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.SAPPHIRE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.RUBY_PAXEL.get()).requires(ModItems.RUBY_SWORD.get()).requires(ModItems.RUBY_PICKAXE.get()).requires(ModItems.RUBY_AXE.get()).requires(ModItems.RUBY_SHOVEL.get()).requires(ModItems.RUBY_HOE.get()).unlockedBy("has_another_ruby_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.RUBY_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.CITRINE_PAXEL.get()).requires(ModItems.CITRINE_SWORD.get()).requires(ModItems.CITRINE_PICKAXE.get()).requires(ModItems.CITRINE_AXE.get()).requires(ModItems.CITRINE_SHOVEL.get()).requires(ModItems.CITRINE_HOE.get()).unlockedBy("has_another_citrine_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CITRINE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.AMETHYST_PAXEL.get()).requires(ModItems.AMETHYST_SWORD.get()).requires(ModItems.AMETHYST_PICKAXE.get()).requires(ModItems.AMETHYST_AXE.get()).requires(ModItems.AMETHYST_SHOVEL.get()).requires(ModItems.AMETHYST_HOE.get()).unlockedBy("has_another_amethyst_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.AMETHYST_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.DIOPSIDE_PAXEL.get()).requires(ModItems.DIOPSIDE_SWORD.get()).requires(ModItems.DIOPSIDE_PICKAXE.get()).requires(ModItems.DIOPSIDE_AXE.get()).requires(ModItems.DIOPSIDE_SHOVEL.get()).requires(ModItems.DIOPSIDE_HOE.get()).unlockedBy("has_another_diopside_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.DIOPSIDE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.JADE_PAXEL.get()).requires(ModItems.JADE_SWORD.get()).requires(ModItems.JADE_PICKAXE.get()).requires(ModItems.JADE_AXE.get()).requires(ModItems.JADE_SHOVEL.get()).requires(ModItems.JADE_HOE.get()).unlockedBy("has_another_jade_gem", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.JADE_GEM.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.CAERULA_PAXEL.get()).requires(ModItems.CAERULA_SWORD.get()).requires(ModItems.CAERULA_PICKAXE.get()).requires(ModItems.CAERULA_AXE.get()).requires(ModItems.CAERULA_SHOVEL.get()).requires(ModItems.CAERULA_HOE.get()).unlockedBy("has_another_caerula_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.CAERULA_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.ENDER_PAXEL.get()).requires(ModItems.ENDER_SWORD.get()).requires(ModItems.ENDER_PICKAXE.get()).requires(ModItems.ENDER_AXE.get()).requires(ModItems.ENDER_SHOVEL.get()).requires(ModItems.ENDER_HOE.get()).unlockedBy("has_another_ender_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.ENDER_INGOT.get()).build())).save(finishedRecipeConsumer);
        ShapelessRecipeBuilder.shapeless(ModItems.FUSION_PAXEL.get()).requires(ModItems.FUSION_SWORD.get()).requires(ModItems.FUSION_PICKAXE.get()).requires(ModItems.FUSION_AXE.get()).requires(ModItems.FUSION_SHOVEL.get()).requires(ModItems.FUSION_HOE.get()).unlockedBy("has_another_fusion_ingot", inventoryTrigger(ItemPredicate.Builder.item().of(ModItems.FUSION_INGOT.get()).build())).save(finishedRecipeConsumer);
    }
}